import React, { ReactElement, useEffect } from "react";

const STORAGE_KEY = "optymaLaunchPopupShown";
const OVERLAY_ID = "optyma-launch-overlay";
const INFO_URL = "https://masternet.euromaster.de/content/page/6abe507033f2521b59e65886";

export const OptymaPopup = (): ReactElement | null => {
  useEffect(() => {
    if (sessionStorage.getItem(STORAGE_KEY)) return;
    if (document.getElementById(OVERLAY_ID)) return;
    const style = document.createElement("style"); style.id="optyma-popup-styles"; style.textContent=`
#${OVERLAY_ID}{position:fixed;inset:0;z-index:2147483647;background:rgba(8,24,53,.64);backdrop-filter:blur(6px);display:flex;align-items:center;justify-content:center;padding:22px;font-family:Montserrat,Arial,sans-serif;color:#17243d}#optyma-popup{position:relative;width:min(700px,100%);background:#fff;border-radius:24px;box-shadow:0 28px 80px rgba(0,0,0,.3);overflow:hidden}.optyma-top{position:relative;background:linear-gradient(135deg,#164194 0%,#0c2d70 68%,#164194 100%);padding:42px 46px 35px;color:#fff;overflow:hidden}.optyma-top:before{content:"";position:absolute;width:290px;height:290px;border-radius:50%;background:#009640;opacity:.17;right:-115px;top:-155px}.optyma-top:after{content:"";position:absolute;width:155px;height:155px;border:28px solid #FEDD00;border-radius:50%;opacity:.08;right:35px;bottom:-110px}.optyma-kicker{position:relative;z-index:1;display:inline-flex;background:#FEDD00;color:#12264a;font-weight:800;font-size:12px;padding:7px 12px;border-radius:999px;margin-bottom:17px;text-transform:uppercase;letter-spacing:.07em}.optyma-top h2{position:relative;z-index:1;font-size:41px;line-height:1.04;margin:0 50px 12px 0;font-weight:850;letter-spacing:-1.1px}.optyma-top p{position:relative;z-index:1;margin:0;font-size:18px;line-height:1.45;max-width:560px;font-weight:500}.optyma-top p strong{font-weight:800}.optyma-close{position:absolute;right:18px;top:17px;width:40px;height:40px;border:0;border-radius:50%;background:rgba(255,255,255,.14);color:#fff;font-size:28px;line-height:38px;cursor:pointer;z-index:3}.optyma-body{padding:27px 46px 32px}.optyma-benefit{font-size:16px;line-height:1.55;color:#35445d;margin:0 0 20px}.optyma-benefit strong{color:#164194}.optyma-promise{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:23px}.optyma-pill{background:#f1f5fb;color:#164194;border-radius:999px;padding:8px 12px;font-size:12.5px;font-weight:750}.optyma-pill:before{content:"✓";color:#009640;font-weight:900;margin-right:6px}.optyma-actions{display:flex;align-items:center;gap:18px;flex-wrap:wrap}.optyma-primary{display:inline-flex;align-items:center;justify-content:center;background:#009640;color:#fff!important;text-decoration:none!important;font-weight:800;font-size:15px;border-radius:11px;padding:13px 20px;box-shadow:0 8px 20px rgba(0,150,64,.18)}.optyma-hint{font-size:12.5px;color:#78849a}@media(max-width:650px){#${OVERLAY_ID}{padding:10px;align-items:flex-end}#optyma-popup{border-radius:20px 20px 0 0}.optyma-top{padding:34px 24px 29px}.optyma-top h2{font-size:34px}.optyma-top p{font-size:16.5px}.optyma-body{padding:23px 24px 27px}.optyma-benefit{font-size:15px}.optyma-actions{align-items:stretch;flex-direction:column;gap:11px}.optyma-hint{text-align:center}}`;
    document.head.appendChild(style);
    const overlay=document.createElement("div"); overlay.id=OVERLAY_ID; overlay.setAttribute("role","dialog"); overlay.setAttribute("aria-modal","true"); overlay.innerHTML=`<div id="optyma-popup"><div class="optyma-top"><button class="optyma-close" type="button" aria-label="Schließen">×</button><div class="optyma-kicker">Coming soon</div><h2>Optyma kommt.</h2><p>Die neue Euromaster-Plattform für <strong>Inspektionen, Arbeitsaufträge und Flotten-Service.</strong></p></div><div class="optyma-body"><p class="optyma-benefit"><strong>Was bringt dir das?</strong> Weniger Systemwechsel, einfachere Abläufe und alle wichtigen Informationen an einem Ort – vom Fahrzeug-Check bis zum Auftrag.</p><div class="optyma-promise"><span class="optyma-pill">Einfacher arbeiten</span><span class="optyma-pill">Schneller zum Auftrag</span><span class="optyma-pill">Mehr Überblick</span></div><div class="optyma-actions"><a class="optyma-primary" href="${INFO_URL}">Das ist Optyma →</a><span class="optyma-hint">Jetzt informieren & auf den Start vorbereiten</span></div></div></div>`; document.body.appendChild(overlay);
    const close=()=>{sessionStorage.setItem(STORAGE_KEY,"true");overlay.remove();style.remove();}; overlay.querySelector(".optyma-close")?.addEventListener("click",close); overlay.querySelector(".optyma-primary")?.addEventListener("click",()=>sessionStorage.setItem(STORAGE_KEY,"true")); const onKeyDown=(e:KeyboardEvent)=>{if(e.key==="Escape")close();}; document.addEventListener("keydown",onKeyDown); return()=>{document.removeEventListener("keydown",onKeyDown);overlay.remove();style.remove();};
  }, []); return null;
};
